#!/bin/bash
echo -e "\n\nbuild hook running...\n"
source ../config/build.env
docker build \
  --build-arg VCS_REF=$VCS_REF \
  --build-arg VCS_URL=$VCS_URL \
  --build-arg VERSION=$VERSION \
  --build-arg BUILD_DATE=$BUILD_DATE \
  --build-arg VENDOR=$VENDOR \
  --build-arg NAME=$NAME \
  --build-arg DESCRIPTION=$DESCRIPTION \
  --build-arg IMAGE_NAME=$IMAGE_NAME \
  -t $IMAGE_NAME .